spring:
  datasource:
    username: bike_park
    password: bike_park
    url: jdbc:mysql://localhost:3306/bike_park
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  
      